package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// shellFunctionsTemplate is what used to be the standalone
// aotools-functions.sh file, now embedded directly in the binary.
// %s is filled in with the absolute path to the running aotools
// executable itself, so `aotools shellinit` always points these
// functions at wherever it actually is on disk -- no separate file,
// no assumptions about install location baked in at compile time.
const shellFunctionsTemplate = `# Generated by "aotools shellinit" -- do not edit by hand; re-run
# "aotools install" (or "aotools shellinit" and re-source) if this
# ever needs regenerating.
#
# A subprocess (aotools itself) can never change its parent shell's
# own working directory, so the actual "cd" into and out of the
# mounted volume has to happen here, in functions sourced into your
# interactive shell -- exactly like the original mountvhd/umountvhd/
# mountchd/umountchd scripts, which also had to be sourced for the
# same reason.

AOTOOLS="%s"

mountvhd() {
    local mp
    mp="$("$AOTOOLS" mount vhd "$1")" || return 1
    AOTOOLS_VHD_PREV_DIR="$PWD"
    cd "$mp" || return 1
}

umountvhd() {
    if [ -n "$AOTOOLS_VHD_PREV_DIR" ] && [ -d "$AOTOOLS_VHD_PREV_DIR" ]; then
        cd "$AOTOOLS_VHD_PREV_DIR"
    else
        cd /tmp
    fi
    "$AOTOOLS" umount vhd
    unset AOTOOLS_VHD_PREV_DIR
}

mountchd() {
    local mp
    mp="$("$AOTOOLS" mount chd "$1")" || return 1
    AOTOOLS_CHD_PREV_DIR="$PWD"
    cd "$mp" || return 1
}

umountchd() {
    if [ -n "$AOTOOLS_CHD_PREV_DIR" ] && [ -d "$AOTOOLS_CHD_PREV_DIR" ]; then
        cd "$AOTOOLS_CHD_PREV_DIR"
    else
        cd /media/fat
    fi
    "$AOTOOLS" umount chd
    unset AOTOOLS_CHD_PREV_DIR
}

mkvhd() {
    if [ "$1" = "-dos" ] || [ "$1" = "-win31" ]; then
        local flag="$1"; shift
        "$AOTOOLS" vhd create "$flag" "$@"
    else
        "$AOTOOLS" vhd create "$@"
    fi
}
resizevhd() { "$AOTOOLS" vhd resize "$@"; }
mkmgl()     { "$AOTOOLS" mgl create "$@"; }
mkchd()     { "$AOTOOLS" chd create "$@"; }
mkima()     { "$AOTOOLS" ima create "$@"; }
`

// selfPath resolves the absolute, symlink-free path to the currently
// running aotools binary, so shellinit/install never have to guess
// or hardcode where they were invoked from.
func selfPath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(exe)
	if err != nil {
		return exe, nil // fall back to the unresolved path rather than fail outright
	}
	return resolved, nil
}

// cmdShellInit implements `aotools shellinit`: prints the
// mountvhd/umountvhd/mountchd/umountchd/mkvhd/resizevhd/mkmgl/mkchd/
// mkima shell functions to stdout, ready to be eval'd. This is the
// same pattern tools like direnv/starship/rbenv use for "one binary,
// no separate files" shell integration:
//
//	eval "$(/media/fat/linux/aotools/aotools shellinit)"
func cmdShellInit() {
	self, err := selfPath()
	if err != nil {
		fatal("could not determine my own executable path: %v", err)
	}
	fmt.Printf(shellFunctionsTemplate, self)
}

// installMarker is a fixed sentinel independent of the running
// binary's own path/name (self path could be /tmp/aotools_test,
// /media/fat/linux/aotools/aotools, or anything else depending on
// where it's run from) -- checking for a literal "aotools shellinit"
// substring instead would miss real installs whenever the binary
// isn't named exactly "aotools" (e.g. "aotools_new" while testing a
// fresh build), silently re-appending a duplicate block every run.
const installMarker = "# --- aotools: mountvhd/umountvhd/mountchd/umountchd/mkvhd/resizevhd/mkmgl/mkchd/mkima ---"

// cmdInstall implements `aotools install`: a one-time, idempotent
// setup step that wires the shell functions into every future shell
// automatically by appending a single `eval "$(... shellinit)"` line
// to user-startup.sh (MiSTer's own boot hook), instead of requiring
// the user to remember to source a separate file by hand. Safe to
// run more than once -- it checks for its own marker before adding
// anything.
func cmdInstall() {
	self, err := selfPath()
	if err != nil {
		fatal("could not determine my own executable path: %v", err)
	}

	evalLine := fmt.Sprintf(`eval "$(%s shellinit)"`, self)

	existing, readErr := os.ReadFile(userStartupPath)
	if readErr == nil && strings.Contains(string(existing), installMarker) {
		eprintf("Already installed: %s already sources aotools's shell functions.\n", userStartupPath)
		eprintln("Nothing to do. (Delete the existing 'aotools shellinit' line there first")
		eprintln("if you want this to re-add it, e.g. after moving the binary.)")
		eprintln()
		missing, qemuBiosMissing, _ := checkDependenciesDetailed()
		eprintln()
		offerFetchMissing(missing, qemuBiosMissing)
		return
	}

	f, err := os.OpenFile(userStartupPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0755)
	if err != nil {
		fatal("could not open %s: %v", userStartupPath, err)
	}
	defer f.Close()

	block := "\n# --- aotools: mountvhd/umountvhd/mountchd/umountchd/mkvhd/resizevhd/mkmgl/mkchd/mkima ---\n" +
		evalLine + "\n"
	if _, err := f.WriteString(block); err != nil {
		fatal("could not write to %s: %v", userStartupPath, err)
	}

	eprintln("Installed.")
	eprintf("Added to %s:\n", userStartupPath)
	eprintf("  %s\n", evalLine)
	eprintln()
	eprintln("Takes effect on next boot / next new shell. To use it in your CURRENT")
	eprintln("shell right now without rebooting, run:")
	eprintf("  eval \"$(%s shellinit)\"\n", self)
	eprintln()
	missing, qemuBiosMissing, _ := checkDependenciesDetailed()
	eprintln()
	offerFetchMissing(missing, qemuBiosMissing)
}

// cmdUninstall implements `aotools uninstall`: the exact reverse of
// the one persistent system change `aotools install` makes -- it
// removes the "# --- aotools: ... ---" comment line and the eval
// line right after it from user-startup.sh, and nothing else.
//
// Deliberately conservative: it does NOT delete the aotools binary,
// does NOT touch any VHD/CHD/game files created with it, and does
// NOT remove any dependency (qemu/chdman/mtools/templates) that
// `install`'s download offer may have fetched -- those are real
// files the user asked for or already had, not install side effects.
// This only ever undoes the shell-function wiring, so a user who
// decides aotools isn't for them can get back to exactly the
// original scripts (which were never touched or removed in the
// first place) with one command instead of hand-editing a system
// file.
func cmdUninstall() {
	existing, err := os.ReadFile(userStartupPath)
	if err != nil {
		if os.IsNotExist(err) {
			eprintf("%s doesn't exist -- nothing to undo.\n", userStartupPath)
			return
		}
		fatal("could not read %s: %v", userStartupPath, err)
	}

	content := string(existing)
	if !strings.Contains(content, installMarker) {
		eprintf("Not installed: %s has no aotools shell-function wiring to remove.\n", userStartupPath)
		return
	}

	lines := strings.Split(content, "\n")
	var kept []string
	skipNext := false
	for _, line := range lines {
		if skipNext {
			// the eval line immediately following the marker comment
			skipNext = false
			continue
		}
		if strings.TrimSpace(line) == installMarker {
			skipNext = true
			// also drop one blank line immediately before the marker
			// (the leading "\n" install's own block starts with), so
			// repeated install/uninstall cycles don't accumulate
			// blank lines in user-startup.sh over time
			if len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
				kept = kept[:len(kept)-1]
			}
			continue
		}
		kept = append(kept, line)
	}

	if err := os.WriteFile(userStartupPath, []byte(strings.Join(kept, "\n")), 0755); err != nil {
		fatal("could not write %s: %v", userStartupPath, err)
	}

	eprintln("Uninstalled.")
	eprintf("Removed aotools's shell-function wiring from %s.\n", userStartupPath)
	eprintln()
	eprintln("Nothing else was touched -- the aotools binary itself, any VHDs/CHDs/")
	eprintln("games you created with it, and any dependency files `install` may have")
	eprintln("downloaded for you earlier are all left exactly as they are. The")
	eprintln("original ao486 DOS Toolkit scripts were never modified in the first")
	eprintln("place, so mountvhd/mkvhd/etc. now resolve back to them as before.")
	eprintln()
	eprintln("Takes effect on next reboot / next new shell. If your CURRENT shell")
	eprintln("already has the functions loaded (e.g. you ran the shellinit eval")
	eprintln("earlier), remove them from just this session with:")
	eprintln("  unset -f mountvhd umountvhd mountchd umountchd mkvhd resizevhd mkmgl mkchd mkima")
}
