package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// shellFunctionsTemplate is what used to be the standalone
// aotools-functions.sh file, now embedded directly in the binary.
// %s is filled in with the absolute path to the running aotools
// executable itself, so `aotools shellinit` always points these
// functions at wherever it actually is on disk -- no separate file,
// no assumptions about install location baked in at compile time.
const shellFunctionsTemplate = `# Generated by "aotools shellinit" -- do not edit by hand; re-run
# "aotools install" (or "aotools shellinit" and re-source) if this
# ever needs regenerating.
#
# A subprocess (aotools itself) can never change its parent shell's
# own working directory, so the actual "cd" into and out of the
# mounted volume has to happen here, in functions sourced into your
# interactive shell -- exactly like the original mountvhd/umountvhd/
# mountchd/umountchd scripts, which also had to be sourced for the
# same reason.

AOTOOLS="%s"

mountvhd() {
    local mp
    mp="$("$AOTOOLS" mount vhd "$1")" || return 1
    AOTOOLS_VHD_PREV_DIR="$PWD"
    cd "$mp" || return 1
}

umountvhd() {
    if [ -n "$AOTOOLS_VHD_PREV_DIR" ] && [ -d "$AOTOOLS_VHD_PREV_DIR" ]; then
        cd "$AOTOOLS_VHD_PREV_DIR"
    else
        cd /tmp
    fi
    "$AOTOOLS" umount vhd
    unset AOTOOLS_VHD_PREV_DIR
}

mountchd() {
    local mp
    mp="$("$AOTOOLS" mount chd "$1")" || return 1
    AOTOOLS_CHD_PREV_DIR="$PWD"
    cd "$mp" || return 1
}

umountchd() {
    if [ -n "$AOTOOLS_CHD_PREV_DIR" ] && [ -d "$AOTOOLS_CHD_PREV_DIR" ]; then
        cd "$AOTOOLS_CHD_PREV_DIR"
    else
        cd /media/fat
    fi
    "$AOTOOLS" umount chd
    unset AOTOOLS_CHD_PREV_DIR
}

mkvhd() {
    if [ "$1" = "-dos" ] || [ "$1" = "-win31" ]; then
        local flag="$1"; shift
        "$AOTOOLS" vhd create "$flag" "$@"
    else
        "$AOTOOLS" vhd create "$@"
    fi
}
resizevhd() { "$AOTOOLS" vhd resize "$@"; }
mkmgl()     { "$AOTOOLS" mgl create "$@"; }
mkchd()     { "$AOTOOLS" chd create "$@"; }
mkima()     { "$AOTOOLS" ima create "$@"; }
`

// selfPath resolves the absolute, symlink-free path to the currently
// running aotools binary, so shellinit/install never have to guess
// or hardcode where they were invoked from.
func selfPath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(exe)
	if err != nil {
		return exe, nil // fall back to the unresolved path rather than fail outright
	}
	return resolved, nil
}

// cmdShellInit implements `aotools shellinit`: prints the
// mountvhd/umountvhd/mountchd/umountchd/mkvhd/resizevhd/mkmgl/mkchd/
// mkima shell functions to stdout, ready to be eval'd. This is the
// same pattern tools like direnv/starship/rbenv use for "one binary,
// no separate files" shell integration:
//
//	eval "$(/media/fat/linux/aotools/aotools shellinit)"
func cmdShellInit() {
	self, err := selfPath()
	if err != nil {
		fatal("could not determine my own executable path: %v", err)
	}
	fmt.Printf(shellFunctionsTemplate, self)
}

// legacyInstallMarker is the single-line marker the very first
// version of `install` wrote (comment line immediately followed by
// just the eval line, nothing else). Kept around permanently so
// `install`/`uninstall` can recognize and safely upgrade/remove a
// block written by that earlier version, rather than assuming every
// real-world install already matches the current begin/end format.
const legacyInstallMarker = "# --- aotools: mountvhd/umountvhd/mountchd/umountchd/mkvhd/resizevhd/mkmgl/mkchd/mkima ---"

// installMarkerBegin/installMarkerEnd delimit the current install
// block, which (unlike the legacy one-marker/one-line format) can
// safely hold any number of lines in between -- this is what makes
// it possible to add the PATH export line below without hand-coding
// "skip exactly N lines after the marker" logic that would silently
// break the moment the block's shape changes again in the future.
const installMarkerBegin = "# --- aotools:begin (shell functions + PATH) ---"
const installMarkerEnd = "# --- aotools:end ---"

// buildInstallBlock renders the full block `install` appends,
// given the resolved self path.
func buildInstallBlock(self string) string {
	dir := filepath.Dir(self)
	pathLine := fmt.Sprintf(`export PATH="$PATH:%s"`, dir)
	evalLine := fmt.Sprintf(`eval "$(%s shellinit)"`, self)
	return "\n" + installMarkerBegin + "\n" +
		pathLine + "\n" +
		evalLine + "\n" +
		installMarkerEnd + "\n"
}

// stripLegacyBlock removes a legacy-format block (marker line + the
// one eval line right after it, plus one preceding blank line) from
// content, matching exactly what the original `uninstall` did.
func stripLegacyBlock(content string) string {
	lines := strings.Split(content, "\n")
	var kept []string
	skipNext := false
	for _, line := range lines {
		if skipNext {
			skipNext = false
			continue
		}
		if strings.TrimSpace(line) == legacyInstallMarker {
			skipNext = true
			if len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
				kept = kept[:len(kept)-1]
			}
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

// stripCurrentBlock removes everything from installMarkerBegin
// through installMarkerEnd (inclusive), plus one preceding blank
// line. Robust to the block containing any number of lines, unlike
// the legacy fixed-offset removal above.
func stripCurrentBlock(content string) string {
	lines := strings.Split(content, "\n")
	var kept []string
	inBlock := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !inBlock && trimmed == installMarkerBegin {
			inBlock = true
			if len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
				kept = kept[:len(kept)-1]
			}
			continue
		}
		if inBlock {
			if trimmed == installMarkerEnd {
				inBlock = false
			}
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

// cmdInstall implements `aotools install`: a one-time, idempotent
// setup step that wires the shell functions AND aotools itself onto
// PATH into every future shell automatically, by appending a small
// block to user-startup.sh (MiSTer's own boot hook), instead of
// requiring the user to remember to source/export anything by hand.
// Safe to run more than once. If it finds a block written by an
// earlier version of aotools (shell functions only, no PATH export),
// it transparently upgrades it to the current format rather than
// leaving two separate blocks or silently not adding PATH.
func cmdInstall() {
	self, err := selfPath()
	if err != nil {
		fatal("could not determine my own executable path: %v", err)
	}
	dir := filepath.Dir(self)

	existing, readErr := os.ReadFile(userStartupPath)
	content := ""
	if readErr == nil {
		content = string(existing)
	}

	if strings.Contains(content, installMarkerBegin) {
		eprintf("Already installed: %s already sources aotools's shell functions\n", userStartupPath)
		eprintln("and has aotools on PATH. Nothing to do.")
		eprintln()
		missing, qemuBiosMissing, _ := checkDependenciesDetailed()
		eprintln()
		offerFetchMissing(missing, qemuBiosMissing)
		return
	}

	upgrading := strings.Contains(content, legacyInstallMarker)
	if upgrading {
		content = stripLegacyBlock(content)
	}

	newContent := content + buildInstallBlock(self)
	if err := os.WriteFile(userStartupPath, []byte(newContent), 0755); err != nil {
		fatal("could not write to %s: %v", userStartupPath, err)
	}

	if upgrading {
		eprintln("Upgraded existing install: your previous aotools setup only wired up")
		eprintln("the shell functions. Re-added it in the current format, which also")
		eprintf("puts aotools itself on PATH (added %s).\n", dir)
	} else {
		eprintln("Installed.")
		eprintf("Added to %s:\n", userStartupPath)
		eprintf(`  export PATH="$PATH:%s"`+"\n", dir)
		eprintf(`  eval "$(%s shellinit)"`+"\n", self)
	}
	eprintln()
	eprintln("Takes effect on next boot / next new shell. To use it in your CURRENT")
	eprintln("shell right now without rebooting, run:")
	eprintf(`  export PATH="$PATH:%s"`+"\n", dir)
	eprintf("  eval \"$(%s shellinit)\"\n", self)
	eprintln()
	missing, qemuBiosMissing, _ := checkDependenciesDetailed()
	eprintln()
	offerFetchMissing(missing, qemuBiosMissing)
}

// cmdUninstall implements `aotools uninstall`: the exact reverse of
// the one persistent system change `aotools install` makes -- it
// removes exactly the block `install` added (shell functions AND,
// in current-format installs, the PATH export) from user-startup.sh,
// and nothing else.
//
// Deliberately conservative: it does NOT delete the aotools binary,
// does NOT touch any VHD/CHD/game files created with it, and does
// NOT remove any dependency (qemu/chdman/mtools/templates) that
// `install`'s download offer may have fetched -- those are real
// files the user asked for or already had, not install side effects.
// This only ever undoes the shell-function/PATH wiring, so a user
// who decides aotools isn't for them can get back to exactly the
// original scripts (which were never touched or removed in the first
// place) with one command instead of hand-editing a system file.
func cmdUninstall() {
	existing, err := os.ReadFile(userStartupPath)
	if err != nil {
		if os.IsNotExist(err) {
			eprintf("%s doesn't exist -- nothing to undo.\n", userStartupPath)
			return
		}
		fatal("could not read %s: %v", userStartupPath, err)
	}
	content := string(existing)

	hasCurrent := strings.Contains(content, installMarkerBegin) && strings.Contains(content, installMarkerEnd)
	hasLegacy := strings.Contains(content, legacyInstallMarker)
	if !hasCurrent && !hasLegacy {
		eprintf("Not installed: %s has no aotools shell-function/PATH wiring to remove.\n", userStartupPath)
		return
	}

	if hasCurrent {
		content = stripCurrentBlock(content)
	}
	if hasLegacy {
		content = stripLegacyBlock(content)
	}

	if err := os.WriteFile(userStartupPath, []byte(content), 0755); err != nil {
		fatal("could not write %s: %v", userStartupPath, err)
	}

	eprintln("Uninstalled.")
	eprintf("Removed aotools's shell-function/PATH wiring from %s.\n", userStartupPath)
	eprintln()
	eprintln("Nothing else was touched -- the aotools binary itself, any VHDs/CHDs/")
	eprintln("games you created with it, and any dependency files `install` may have")
	eprintln("downloaded for you earlier are all left exactly as they are. The")
	eprintln("original ao486 DOS Toolkit scripts were never modified in the first")
	eprintln("place, so mountvhd/mkvhd/etc. now resolve back to them as before.")
	eprintln()
	eprintln("Takes effect on next reboot / next new shell. If your CURRENT shell")
	eprintln("already has the functions/PATH loaded, remove them from just this")
	eprintln("session with:")
	eprintln("  unset -f mountvhd umountvhd mountchd umountchd mkvhd resizevhd mkmgl mkchd mkima")
	eprintln(`  (PATH itself will only revert to normal in a fresh shell)`)
}
