package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// shellFunctionsTemplate is what used to be the standalone
// aotools-functions.sh file, now embedded directly in the binary.
// %s is filled in with the absolute path to the running aotools
// executable itself, so `aotools shellinit` always points these
// functions at wherever it actually is on disk -- no separate file,
// no assumptions about install location baked in at compile time.
//
// The key piece here is the `aotools` shell function itself. A
// subprocess (the compiled binary) can never change its parent
// shell's own working directory -- that's a hard OS limitation, not
// something this tool can work around by being cleverer. So instead
// of `aotools` on your PATH ever resolving straight to the binary,
// `install`/`shellinit` define `aotools` itself as a shell function:
// it special-cases `mount vhd`/`umount vhd`/`mount chd`/`umount chd`
// to do the actual cd in your live shell (remembering where you were
// so umount can put you back), and passes every other subcommand
// straight through to the real binary via $AOTOOLS untouched. Because
// bash looks up shell functions before PATH, typing `aotools ...` at
// the prompt always goes through this wrapper once it's loaded -- so
// `aotools mount vhd x.vhd` and the legacy `mountvhd x.vhd` shortcut
// below are literally the same code path, sharing the same
// AOTOOLS_VHD_PREV_DIR/AOTOOLS_CHD_PREV_DIR state, and behave
// identically. (Only if you invoke the binary by its full path
// directly, bypassing the shell entirely, do you get the raw
// non-cd'ing behavior -- there's no other way to do it.)
const shellFunctionsTemplate = `# Generated by "aotools shellinit" -- do not edit by hand; re-run
# "aotools install" (or "aotools shellinit" and re-source) if this
# ever needs regenerating.

AOTOOLS="%s"

aotools() {
    case "$1 $2" in
        "mount vhd")
            local mp
            mp="$("$AOTOOLS" mount vhd "$3")" || return 1
            AOTOOLS_VHD_PREV_DIR="$PWD"
            cd "$mp" || return 1
            ;;
        "umount vhd")
            if [ -n "$AOTOOLS_VHD_PREV_DIR" ] && [ -d "$AOTOOLS_VHD_PREV_DIR" ]; then
                cd "$AOTOOLS_VHD_PREV_DIR"
            else
                cd /tmp
            fi
            "$AOTOOLS" umount vhd
            unset AOTOOLS_VHD_PREV_DIR
            ;;
        "mount chd")
            local mp
            mp="$("$AOTOOLS" mount chd "$3")" || return 1
            AOTOOLS_CHD_PREV_DIR="$PWD"
            cd "$mp" || return 1
            ;;
        "umount chd")
            if [ -n "$AOTOOLS_CHD_PREV_DIR" ] && [ -d "$AOTOOLS_CHD_PREV_DIR" ]; then
                cd "$AOTOOLS_CHD_PREV_DIR"
            else
                cd /media/fat
            fi
            "$AOTOOLS" umount chd
            unset AOTOOLS_CHD_PREV_DIR
            ;;
        *)
            "$AOTOOLS" "$@"
            ;;
    esac
}

# Legacy short names -- kept for anyone used to the original ao486 DOS
# Toolkit script names. All of these just call the aotools() function
# above, so they share its exact cd behavior and state; they are not
# a second, separately-behaving code path.
mountvhd()   { aotools mount vhd "$1"; }
umountvhd()  { aotools umount vhd; }
mountchd()   { aotools mount chd "$1"; }
umountchd()  { aotools umount chd; }
mkvhd() {
    if [ "$1" = "-dos" ] || [ "$1" = "-win31" ]; then
        local flag="$1"; shift
        aotools vhd create "$flag" "$@"
    else
        aotools vhd create "$@"
    fi
}
resizevhd() { aotools vhd resize "$@"; }
mkmgl()     { aotools mgl create "$@"; }
mkchd()     { aotools chd create "$@"; }
mkima()     { aotools ima create "$@"; }

# Real MS-DOS/Windows 3.1 needs CRLF line endings in text files like
# CONFIG.SYS/AUTOEXEC.BAT; nano over an SSH session saves plain LF, which
# real hardware won't parse correctly. This wrapper runs the real nano
# (via "command nano", bypassing this function to avoid recursing) and
# then, for any file argument that's inside a mounted VHD or CHD, runs
# unix2dos on it automatically so you never have to remember to do it
# by hand. Files outside a mount are left completely alone.
nano() {
    command nano "$@"
    local rc=$?
    local f rp converted=0
    for f in "$@"; do
        case "$f" in
            -*) continue ;;
        esac
        [ -f "$f" ] || continue
        rp="$(readlink -f "$f" 2>/dev/null)"
        case "$rp" in
            /tmp/vhd_mount/*|/media/fat/linux/.mountchd_mount/*)
                if command -v unix2dos >/dev/null 2>&1; then
                    unix2dos "$f" >/dev/null 2>&1
                    converted=1
                fi
                ;;
        esac
    done
    if [ "$converted" = "1" ]; then
        echo "(converted to DOS line endings for real hardware compatibility)" >&2
    fi
    return $rc
}
`

// selfPath resolves the absolute, symlink-free path to the currently
// running aotools binary, so shellinit/install never have to guess
// or hardcode where they were invoked from.
func selfPath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(exe)
	if err != nil {
		return exe, nil // fall back to the unresolved path rather than fail outright
	}
	return resolved, nil
}

// cmdShellInit implements `aotools shellinit`: prints the
// mountvhd/umountvhd/mountchd/umountchd/mkvhd/resizevhd/mkmgl/mkchd/
// mkima shell functions to stdout, ready to be eval'd. This is the
// same pattern tools like direnv/starship/rbenv use for "one binary,
// no separate files" shell integration:
//
//	eval "$(/media/fat/linux/aotools/aotools shellinit)"
func cmdShellInit() {
	self, err := selfPath()
	if err != nil {
		fatal("could not determine my own executable path: %v", err)
	}
	fmt.Printf(shellFunctionsTemplate, self)
}

// legacyInstallMarker is the single-line marker the very first
// version of `install` wrote (comment line immediately followed by
// just the eval line, nothing else). Kept around permanently so
// `install`/`uninstall` can recognize and safely upgrade/remove a
// block written by that earlier version, rather than assuming every
// real-world install already matches the current begin/end format.
const legacyInstallMarker = "# --- aotools: mountvhd/umountvhd/mountchd/umountchd/mkvhd/resizevhd/mkmgl/mkchd/mkima ---"

// installMarkerBegin/installMarkerEnd delimit the current install
// block, which (unlike the legacy one-marker/one-line format) can
// safely hold any number of lines in between -- this is what makes
// it possible to change what the block does without hand-coding
// "skip exactly N lines after the marker" logic that would silently
// break the moment the block's shape changes again in the future.
const installMarkerBegin = "# --- aotools:begin (shell functions + PATH) ---"
const installMarkerEnd = "# --- aotools:end ---"

// profileDHeredocTag is just the heredoc delimiter used inside the
// user-startup.sh block below. Quoted (<<'TAG') so the shell does
// NOT expand $PATH/$(...) at write time -- we want those written out
// as literal text into profileDPath, to be expanded later when a
// login shell actually sources that file.
const profileDHeredocTag = "AOTOOLS_PROFILE_EOF"

// buildProfileDContent renders what actually goes into profileDPath:
// the PATH export plus the shell-function eval, exactly what a login
// shell needs sourced into it.
func buildProfileDContent(self string) string {
	dir := filepath.Dir(self)
	return fmt.Sprintf("export PATH=\"$PATH:%s\"\neval \"$(%s shellinit)\"\n", dir, self)
}

// buildInstallBlock renders the full block `install` appends to
// user-startup.sh. IMPORTANT: this does NOT export/eval anything
// directly -- user-startup.sh runs once, as its own standalone child
// process of the boot init system, so anything exported there dies
// with that process and never reaches SSH sessions opened later (this
// was a real bug: an earlier version of this block ran export/eval
// directly here, which silently did nothing for any shell other than
// user-startup.sh's own). Instead, this block (re)writes profileDPath
// on every boot, which IS sourced by every login shell via
// /etc/profile's own "for i in /etc/profile.d/*.sh" loop.
func buildInstallBlock(self string) string {
	body := buildProfileDContent(self)
	return "\n" + installMarkerBegin + "\n" +
		fmt.Sprintf("cat > %s <<'%s'\n", profileDPath, profileDHeredocTag) +
		body +
		profileDHeredocTag + "\n" +
		installMarkerEnd + "\n"
}

// blockIsUpToDate reports whether the install block already present
// in content uses the current profileDPath-writing mechanism, as
// opposed to an older version of this block that tried to export/
// eval directly (which never actually worked for new SSH sessions).
func blockIsUpToDate(content string) bool {
	start := strings.Index(content, installMarkerBegin)
	end := strings.Index(content, installMarkerEnd)
	if start == -1 || end == -1 || end < start {
		return false
	}
	return strings.Contains(content[start:end], profileDPath)
}

// stripLegacyBlock removes a legacy-format block (marker line + the
// one eval line right after it, plus one preceding blank line) from
// content, matching exactly what the original `uninstall` did.
func stripLegacyBlock(content string) string {
	lines := strings.Split(content, "\n")
	var kept []string
	skipNext := false
	for _, line := range lines {
		if skipNext {
			skipNext = false
			continue
		}
		if strings.TrimSpace(line) == legacyInstallMarker {
			skipNext = true
			if len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
				kept = kept[:len(kept)-1]
			}
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

// stripCurrentBlock removes everything from installMarkerBegin
// through installMarkerEnd (inclusive), plus one preceding blank
// line. Robust to the block containing any number of lines, unlike
// the legacy fixed-offset removal above.
func stripCurrentBlock(content string) string {
	lines := strings.Split(content, "\n")
	var kept []string
	inBlock := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !inBlock && trimmed == installMarkerBegin {
			inBlock = true
			if len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
				kept = kept[:len(kept)-1]
			}
			continue
		}
		if inBlock {
			if trimmed == installMarkerEnd {
				inBlock = false
			}
			continue
		}
		kept = append(kept, line)
	}
	return strings.Join(kept, "\n")
}

// cmdInstall implements `aotools install`: a one-time, idempotent
// setup step that wires the shell functions AND aotools itself onto
// PATH into every future shell automatically. Safe to run more than
// once.
//
// The actual mechanism: user-startup.sh (persistent, on /media/fat,
// run once per boot) is given a block that (re)writes profileDPath
// (/etc/profile.d/aotools.sh) every boot. /etc/profile itself sources
// every *.sh file under /etc/profile.d/ for every login shell, so
// that's what actually reaches new SSH sessions -- user-startup.sh's
// own export/eval never would (see the long comment on
// buildInstallBlock). This function also writes profileDPath directly,
// right now, so a new SSH session works immediately without waiting
// for a reboot.
//
// If it finds a block written by an earlier version of aotools --
// either the very first (shell functions only, no PATH) or the
// version right after that (which exported/evaled directly in
// user-startup.sh and silently didn't work for new SSH sessions) --
// it transparently upgrades to the current mechanism rather than
// leaving stale/broken blocks around.
func cmdInstall() {
	self, err := selfPath()
	if err != nil {
		fatal("could not determine my own executable path: %v", err)
	}
	dir := filepath.Dir(self)

	existing, readErr := os.ReadFile(userStartupPath)
	content := ""
	if readErr == nil {
		content = string(existing)
	}

	hasLegacy := strings.Contains(content, legacyInstallMarker)
	hasCurrentBlock := strings.Contains(content, installMarkerBegin) && strings.Contains(content, installMarkerEnd)

	if hasCurrentBlock && blockIsUpToDate(content) {
		eprintf("Already installed: %s already sources aotools's shell functions\n", userStartupPath)
		eprintln("and has aotools on PATH for every new SSH session. Nothing to do.")
		if err := os.WriteFile(profileDPath, []byte(buildProfileDContent(self)), 0644); err != nil {
			eprintf("warning: could not refresh %s: %v\n", profileDPath, err)
		}
		eprintln()
		missing, qemuBiosMissing, _ := checkDependenciesDetailed()
		eprintln()
		offerFetchMissing(missing, qemuBiosMissing)
		return
	}

	upgrading := hasLegacy || hasCurrentBlock
	if hasLegacy {
		content = stripLegacyBlock(content)
	}
	if hasCurrentBlock {
		content = stripCurrentBlock(content)
	}

	newContent := content + buildInstallBlock(self)
	if err := os.WriteFile(userStartupPath, []byte(newContent), 0755); err != nil {
		fatal("could not write to %s: %v", userStartupPath, err)
	}

	if err := os.WriteFile(profileDPath, []byte(buildProfileDContent(self)), 0644); err != nil {
		eprintf("warning: could not write %s: %v\n", profileDPath, err)
		eprintln("(user-startup.sh was updated regardless -- this will take effect on next boot)")
	}

	if upgrading {
		eprintln("Upgraded existing install.")
		eprintln("Your previous setup wired PATH/shell functions directly into")
		eprintln("user-startup.sh's own one-time boot process, which never actually reached")
		eprintln("later SSH sessions -- that's why `aotools <command>` could report")
		eprintln("\"command not found\" even after a reboot. Fixed: user-startup.sh now")
		eprintf("(re)writes %s on every boot, which IS sourced by every\n", profileDPath)
		eprintln("new login shell, and it's also been written right now so you don't have")
		eprintln("to reboot to pick it up.")
	} else {
		eprintln("Installed.")
		eprintf("Added a block to %s that (re)creates %s\n", userStartupPath, profileDPath)
		eprintln("on every boot -- that file puts aotools on PATH and loads the shell")
		eprintln("functions for every new login shell. Also wrote it right now, for")
		eprintln("immediate effect.")
	}
	eprintln()
	eprintln("Open a NEW SSH session and `aotools`, `mountvhd`, `mkvhd`, etc. will just")
	eprintln("work -- no reboot needed. Your CURRENT shell won't see it (PATH is only")
	eprintln("read when a shell starts); to use it in this session right now instead,")
	eprintln("run:")
	eprintf(`  export PATH="$PATH:%s"`+"\n", dir)
	eprintf("  eval \"$(%s shellinit)\"\n", self)
	eprintln()
	missing, qemuBiosMissing, _ := checkDependenciesDetailed()
	eprintln()
	offerFetchMissing(missing, qemuBiosMissing)
}

// cmdUninstall implements `aotools uninstall`: the exact reverse of
// the one persistent system change `aotools install` makes -- it
// removes exactly the block `install` added (shell functions AND,
// in current-format installs, the PATH export) from user-startup.sh,
// and nothing else.
//
// Deliberately conservative: it does NOT delete the aotools binary,
// does NOT touch any VHD/CHD/game files created with it, and does
// NOT remove any dependency (qemu/chdman/mtools/templates) that
// `install`'s download offer may have fetched -- those are real
// files the user asked for or already had, not install side effects.
// This only ever undoes the shell-function/PATH wiring, so a user
// who decides aotools isn't for them can get back to exactly the
// original scripts (which were never touched or removed in the first
// place) with one command instead of hand-editing a system file.
func cmdUninstall() {
	existing, err := os.ReadFile(userStartupPath)
	if err != nil && !os.IsNotExist(err) {
		fatal("could not read %s: %v", userStartupPath, err)
	}
	content := string(existing)

	hasCurrent := strings.Contains(content, installMarkerBegin) && strings.Contains(content, installMarkerEnd)
	hasLegacy := strings.Contains(content, legacyInstallMarker)
	profileDExists := fileExists(profileDPath)

	if !hasCurrent && !hasLegacy && !profileDExists {
		eprintf("Not installed: %s has no aotools shell-function/PATH wiring to remove.\n", userStartupPath)
		return
	}

	if hasCurrent {
		content = stripCurrentBlock(content)
	}
	if hasLegacy {
		content = stripLegacyBlock(content)
	}

	if hasCurrent || hasLegacy {
		if err := os.WriteFile(userStartupPath, []byte(content), 0755); err != nil {
			fatal("could not write %s: %v", userStartupPath, err)
		}
	}

	if profileDExists {
		if err := os.Remove(profileDPath); err != nil {
			eprintf("warning: could not remove %s: %v\n", profileDPath, err)
		}
	}

	eprintln("Uninstalled.")
	eprintf("Removed aotools's shell-function/PATH wiring from %s", userStartupPath)
	if profileDExists {
		eprintf(" and deleted %s", profileDPath)
	}
	eprintln(".")
	eprintln()
	eprintln("Nothing else was touched -- the aotools binary itself, any VHDs/CHDs/")
	eprintln("games you created with it, and any dependency files `install` may have")
	eprintln("downloaded for you earlier are all left exactly as they are. The")
	eprintln("original ao486 DOS Toolkit scripts were never modified in the first")
	eprintln("place, so mountvhd/mkvhd/etc. now resolve back to them as before.")
	eprintln()
	eprintln("Takes effect immediately for any NEW SSH session (and, naturally, survives")
	eprintln("future reboots too, since nothing recreates the wiring anymore). If your")
	eprintln("CURRENT shell already has the functions/PATH loaded, remove them from just")
	eprintln("this session with:")
	eprintln("  unset -f mountvhd umountvhd mountchd umountchd mkvhd resizevhd mkmgl mkchd mkima")
	eprintln(`  (PATH itself will only revert to normal in a fresh shell)`)
}
